version: '3.9'
services:
  dev-database:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nest_development
    ports:
      - "5432:5432"
    restart: always
    networks:
      - dev
networks:
  dev: