version: '3.9'
services:
  dev-database:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_development
    ports:
      - "5432:5432"
    networks:
      - test
networks:
  test: