# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgresql://postgres:${{ secrets.SECRET_PASSWORD }}@localhost:5432/nest_development
      NODE_ENV: 'test'
      ENVIRONMENT_TITLE: 'Test-Server'
      SERVER_PORT: 1337
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      # need checkout before using compose-action
      - uses: actions/checkout@v2

      - uses: isbang/compose-action@v1.0.0
        with:
          compose-file: './docker/docker-compose.dev.yml'
          down-flags: '--volumes'

      # - uses: actions/checkout@v2

      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install # will run `yarn install` command

      - name: Get Info
        run: docker logs docker_dev-database_1

      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: prisma:migrate:dev # will run `yarn prisma:migrate:dev` command

      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build # will run `yarn build` command

      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test # will run `yarn test` command
