name: Node.js Test Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DATABASE_URL: postgresql://postgres:${{ secrets.SECRET_PASSWORD }}@0.0.0.0:5432/test_development
  NODE_ENV: 'test'
  ENVIRONMENT_TITLE: 'Test-Server'
  SERVER_PORT: 1337
  JWT_SECRET: ${{ secrets.JWT_SECRET }}

jobs:
  setup-posgres:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Posgres
        run: docker-compose -f docker/docker-compose.test.yml up -d
      - name: Wait for Postgres
        run: sleep 10
      - name: Setup Database
        run: docker exec -i postgres psql -U postgres -c "CREATE DATABASE test_development;"

  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          yarn: true
      - name: Install dependencies
        run: yarn install

  build:
    runs-on: ubuntu-latest
    depends-on: install
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: yarn build

  migrate:
    runs-on: ubuntu-latest
    depends-on: build
    steps:
      - uses: actions/checkout@v2
      - name: Migrate
        run: npx prisma migrate deploy

  test:
    runs-on: ubuntu-latest
    depends-on: build
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: yarn test
