name: Node.js Test Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DATABASE_URL: postgresql://postgres:${{ secrets.SECRET_PASSWORD }}@0.0.0.0:5432/test_development
  NODE_ENV: 'test'
  ENVIRONMENT_TITLE: 'Test-Server'
  SERVER_PORT: 1337
  JWT_SECRET: ${{ secrets.JWT_SECRET }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Posgres
        run: docker-compose -f docker/docker-compose.test.yml up -d

      # - run: export DB_URL=$DATABASE_URL && echo $DB_URL

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
          check-latest: true
      - run: yarn install

      - run: yarn build

      - name: Migrate
        run: npx prisma migrate deploy

      - name: Run Tests
        run: yarn test
